 
1. [Regresión Logística](#id1)
2. [Random Forest](#id2)



In [111]:
%pip install nltk

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: nltk in c:\users\alexc\appdata\local\programs\python\python310\lib\site-packages (3.8.1)




[notice] A new release of pip is available: 23.0.1 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [112]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from string import punctuation

import nltk
nltk.download('stopwords')

import pickle
import datetime as dt

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\alexc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

### Sacamos el dataframe final

In [113]:
df = pd.read_csv('../data/processed/Reviews_FINAL.csv',index_col=0)
df.dropna(inplace=True)

In [157]:
lista_target = []
for i in df['Estrellas']:
    if i < 4: 
        lista_target.append(0)
    else:
        lista_target.append(1)

df['Target'] = lista_target

In [158]:
df

Estrellas                                            Reseñas  \
0              5  Fiable con servicio al comprador incomparable....   
1              1  Amazon exige que le entregue la firma del vend...   
2              1  Hace unos días compré un lote y la… Hace unos ...   
3              5  Amazon muy buena experiencia Años haciendo ped...   
4              1  La peor tienda online Es un completo asco de t...   
...          ...                                                ...   
92344          5  Siempre perfectos Siempre perfectos.  Y tuve q...   
92345          5  Bueno de momento bien Bueno de momento bien. a...   
92346          5  Muy fácil realizar la reserva Muy fácil realiz...   
92347          5  Fácil cómodo y económico Fácil cómodo y económ...   
92348          5                                      todo perfecto   

       Sentimiento                                    Texto procesado  Target  
0                1  fiabl con servici al comprador incompar total ...       1  
1                0  amazon exig que le entreg la firm del vendedor...       0  
2                0  hac unos dias compr un lot y la… hac unos dias...       0  
3                1  amazon muy buen experient años hac ped siend p...       1  
4                0  la peor tiend onlin es un complet asco de tien...       0  
...            ...                                                ...     ...  
92344            1  siempr perfect siempr perfect y tuv que utiliz...       1  
92345            1  buen de moment bien buen de moment bien a ver ...       1  
92346            1  muy facil realiz la reserv muy facil realiz la...       1  
92347            1  facil comod y econom facil comod y econom buen...       1  
92348            1                                        tod perfect       1  

[92338 rows x 5 columns]

## Regresión Logística <a name="id1"></a>


#### Probamos con CountVectorizer

In [151]:
for i in range(3,7):
    X_train, X_test, y_train, y_test = train_test_split(df['Texto procesado'], df['Target'], test_size=0.2)

    vectorizer = CountVectorizer(ngram_range = (1,3))
    X_train_vectors = vectorizer.fit_transform(X_train)
    X_test_vectors = vectorizer.transform(X_test)

    classifier = LogisticRegression(C=i)
    classifier.fit(X_train_vectors, y_train)

    y_pred = classifier.predict(X_test_vectors)
    accuracy = accuracy_score(y_test, y_pred)
    print("Precisión del modelo:", accuracy)

    confusion_matrix(y_test, y_pred)
    

    

c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Precisión del modelo: 0.9529997834091402


c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Precisión del modelo: 0.9520792722547109


c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Precisión del modelo: 0.9505631362356508
Precisión del modelo: 0.9502923976608187


c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#### Comprobación del modelo

----

In [159]:
df_predicciones = pd.DataFrame()
df_predicciones['Real'] = y_test
df_predicciones['Predicción'] = y_pred
df_predicciones['Texto procesado'] = X_test
df_predicciones_mal = df_predicciones[df_predicciones['Real'] - df_predicciones['Predicción'] != 0]

In [160]:
df_predicciones_mal.merge(df, how = 'inner', on = 'Texto procesado')

Real  Predicción                                    Texto procesado  \
0        1           0  hay siti dond aun no se… hay siti dond aun no ...   
1        1           0  econom en compar al rest de la… econom en comp...   
2        1           0  por tra el paquet por la tard por tra el paque...   
3        0           1                  me ha hech dos carg del mism viaj   
4        0           1                                       bastant bien   
...    ...         ...                                                ...   
1254     0           1  la verd estoy asust con las… la verd estoy asu...   
1255     0           1  hac años funcion bien hac años funcion bien ul...   
1256     1           0  este es mi rating este es mi rating deb a un p...   
1257     1           0  en el preci per el apartament muy… en el preci...   
1258     0           1  los trasl entre aeropuert es muy… los trasl en...   

      Estrellas                                            Reseñas  \
0             4  Hay sitios donde aún no se… Hay sitios donde a...   
1             4  ECONOMICO  EN  COMPARACION  AL  RESTO  DE  LA…...   
2             5  Por traerme el paquete por la tarde Por traerm...   
3             1             Me ha hecho dos cargos del mismo viaje   
4             5                                      Bastante bien   
...         ...                                                ...   
1254          1  La verdad estoy asustada con las… La verdad es...   
1255          2  Hace años funcionaban bien Hace años funcionab...   
1256          4  Este es mi rating Este es mi rating, debido a ...   
1257          5  En el precio pero el apartamento muy… En el pr...   
1258          1  Los traslados entre aeropuertos es muy… Los tr...   

      Sentimiento  Target  
0               1       1  
1               1       1  
2               1       1  
3               0       0  
4               1       1  
...           ...     ...  
1254            0       0  
1255            0       0  
1256            1       1  
1257            1       1  
1258            0       0  

[1259 rows x 7 columns]

In [129]:
df_comprobacion  = df_predicciones[df_predicciones['Real']-df_predicciones['Predicción']!= 0]
df_comprobacion.iloc[0,-1]

'atencion al client el chic que atendi no entendi el… el chic que atendi no entendi el catal en barcelon es rar trabaj en la tiend de francesc maci por suert yo habl catal ycastellan pud cambi graci'

In [120]:
df_predicciones['Predicción'].value_counts()

1    10167
0     8301
Name: Predicción, dtype: int64

In [130]:
from nltk.stem.snowball import SnowballStemmer

stopwords = nltk.corpus.stopwords.words('spanish')
stemmer = SnowballStemmer("spanish")
def preprocess_text(text):
    # Eliminar puntuación
    text = ''.join([c for c in text if c not in punctuation])

    # Convertir a minúsculas
    text = text.lower()

    # Tokenización
    tokens = nltk.word_tokenize(text)

    # # Eliminar palabras de parada
    # tokens = [word for word in tokens if word not in stopwords]

    #Aplicar un stemmer
    stemmed_tokens = [stemmer.stem(token) for token in tokens]
    stemmed_text = " ".join(stemmed_tokens)
    return stemmed_text

In [131]:
new_text = """
De momento solo he hecho la reserva, pero me ha resultado sencillo y además me ha ofrecido mejor precio que otro comparados."""

processed_text = preprocess_text(new_text)
new_text_vector = vectorizer.transform([processed_text])
prediction = classifier.predict(new_text_vector)
prediction


array([1], dtype=int64)

In [15]:
print(new_text)
print(processed_text)
print(new_text_vector)

puntajes_tfidf = new_text_vector.toarray()[0]
print(puntajes_tfidf)
vocabulario = vectorizer.vocabulary_



Ya hemos comprado tres ventiladores en Create, son muy bonitos y funcionan muy bien, solo he tenido alguna incidencia con el wifi que se desconfigura de vez en cuando, pero recomiendo los ventiladores cien por cien.
La empresa me parece muy seria y tiene muy buena calidad.
Pongo 4 estrellas porque nunca pongo 5 pero realmente estoy muy contenta
compr tres ventil creat bonit funcion bien sol algun incident wifi desconfigur vez recom ventil cien cien empres parec seri buen calid pong 4 estrell nunc pong 5 realment content
  (0, 126192)	1
  (0, 127479)	1
  (0, 263231)	1
  (0, 270509)	1
  (0, 270513)	1
  (0, 282164)	1
  (0, 290423)	1
  (0, 291792)	1
  (0, 314553)	1
  (0, 374448)	2
  (0, 374460)	1
  (0, 442204)	1
  (0, 461776)	1
  (0, 461800)	1
  (0, 508696)	1
  (0, 548734)	1
  (0, 636633)	1
  (0, 788669)	1
  (0, 792862)	1
  (0, 792878)	1
  (0, 887499)	1
  (0, 888340)	1
  (0, 983555)	1
  (0, 983914)	1
  (0, 984148)	1
  (0, 1112168)	1
  (0, 1417189)	1
  (0, 1420311)	1
  (0, 1495050)	1
  (0, 

## Grid Search CV <a name="id2"></a>

Vamos a probar con un Grid Search CV

In [52]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [162]:
X_train, X_test, y_train, y_test = train_test_split(df['Texto procesado'], df['Target'], test_size=0.2)

vectorizer = CountVectorizer(ngram_range=(1,3))
X_train_vectors = vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_test)

pipe = Pipeline(steps=[("classifier", LogisticRegression())])

logistic_params = {
    'classifier': [LogisticRegression()],
    'classifier__penalty': ['l1','l2'],
    'classifier__C': [1,2.5,3,3.5,4]
}

search_space = [logistic_params]

grid = GridSearchCV(pipe,
                   search_space,
                   cv = 10,
                   n_jobs=-1)

grid.fit(X_train_vectors, y_train)

c:\Users\alexc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('classifier', LogisticRegression())]),
             n_jobs=-1,
             param_grid=[{'classifier': [LogisticRegression(C=1)],
                          'classifier__C': [1, 2.5, 3, 3.5, 4],
                          'classifier__penalty': ['l2']}])

In [163]:
print("Best estimator:", grid.best_estimator_)
print("Best params:", grid.best_params_)
print("Best score:", grid.best_score_)

Best estimator: Pipeline(steps=[('classifier', LogisticRegression(C=1))])
Best params: {'classifier': LogisticRegression(C=1), 'classifier__C': 1, 'classifier__penalty': 'l2'}
Best score: 0.9499661567618789


In [57]:
y_pred = grid.predict(X_test_vectors)
confusion_matrix(y_test, y_pred)

array([[7714,  587],
       [ 404, 9277]], dtype=int64)

In [58]:
import pickle

filename = 'nlp_model_3.pkl'
pickle.dump(grid, open(filename,'wb'))




----

## XGBoost

In [24]:
%pip install xgboost

     ---------------------------------------- 0.0/70.9 MB ? eta -:--:--
     ---------------------------------------- 0.3/70.9 MB 7.9 MB/s eta 0:00:09
     ---------------------------------------- 0.5/70.9 MB 6.0 MB/s eta 0:00:12
     ---------------------------------------- 0.7/70.9 MB 5.8 MB/s eta 0:00:13
      --------------------------------------- 0.9/70.9 MB 5.6 MB/s eta 0:00:13
      --------------------------------------- 1.2/70.9 MB 5.4 MB/s eta 0:00:13
      --------------------------------------- 1.7/70.9 MB 6.5 MB/s eta 0:00:11
     - -------------------------------------- 2.3/70.9 MB 7.3 MB/s eta 0:00:10
     - -------------------------------------- 2.7/70.9 MB 7.4 MB/s eta 0:00:10
     - -------------------------------------- 2.8/70.9 MB 6.9 MB/s eta 0:00:10
     - -------------------------------------- 3.1/70.9 MB 6.8 MB/s eta 0:00:10
     - -------------------------------------- 3.2/70.9 MB 6.3 MB/s eta 0:00:11
     - -------------------------------------- 3.5/70.9 MB 6


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [59]:
import xgboost

In [161]:
X_train, X_val, y_train, y_val = train_test_split(df['Texto procesado'], df['Target'], test_size=0.2, random_state=42)


vectorizer = CountVectorizer(ngram_range=(1,3))
X_train_vectors = vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_val)

xgb = xgboost.XGBClassifier(n_estimators = 500,max_depth = 5, n_jobs = -1, early_stopping_rounds = 28)
xgb.fit(X_train_vectors,y_train, eval_set = [(X_test_vectors, y_val)])



[0]	validation_0-logloss:0.53929


KeyboardInterrupt: 

In [ ]:
pred = xgb.predict(X_test_vectors)
pred_train = xgb.predict(X_train_vectors)
xgb.score(X_test_vectors, y_val)

0.945148364739008

In [ ]:
confusion_matrix(y_val, pred)

array([[7971,  524],
       [ 489, 9484]], dtype=int64)

## CatBoost Classifier

In [22]:
from catboost import CatBoostClassifier

X_train, X_test, y_train, y_test = train_test_split(df['Texto procesado'], df['Target'], test_size=0.2)

vectorizer = CountVectorizer(ngram_range=(1,3))
X_train_vectors = vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_test)

model = CatBoostClassifier(iterations=100, learning_rate=0.1, random_state=42)
model.fit(X_train_vectors, y_train, verbose=False)

# Realizar predicciones en el conjunto de prueba
y_pred = model.predict(X_test_vectors)

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo: {:.2f}%".format(accuracy * 100))

Precisión del modelo: 92.65%


In [23]:
confusion_matrix(y_test, y_pred)

array([[6453,  750],
       [ 372, 7700]], dtype=int64)